// <auto-generated />
using Filmstudion.api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Filmstudion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220208132449_hej")]
    partial class hej
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Filmstudion.api.Models.Filmstudio", b =>
                {
                    b.Property<int>("FilmStudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FilmStudioId");

                    b.ToTable("Filmstudios");

                    b.HasData(
                        new
                        {
                            FilmStudioId = 1,
                            City = "Göteborg",
                            Name = "Testis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
